trigger:
- master

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:ddMMyyyy)

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_Tests
  displayName: Build & Run Tests
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Essai gratuit(59d7c384-c2c9-4648-8862-b722fba18e35)'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up -d'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*.xml'
