version: '3'

services:
  back:
    build: ./theme01/
    container_name: back
    environment:
      - PORT=4000
      - HOST="127.0.0.1"
      - DBHOST=db
      - DBNAME=gotham_dev
      - SECRET_KEY_BASE=secret
    expose:
      - "4000"
    ports:
      - "4000:4000"
    networks:
      - db-network
    depends_on:
      - db
  front:
    build: ./theme02/
    container_name: front
    ports:
      - "80:8080"
    networks:
      - db-network
    depends_on:
      - back
  db:
    build: .
    container_name: gotham-db
    restart: always
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - db-network
  test:
      build:
        context: .
        dockerfile: test.Dockerfile
      volumes:
          - .:/app
      depends_on:
        - db
volumes:
  gotham_db: {}
networks:
  db-network:
